services:
  postgresql:
    container_name: ms_pg_projectdev
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres_projectdev:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - projectdev
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_projectdev:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - projectdev
    restart: unless-stopped

networks:
  projectdev:
    driver: bridge

volumes:
  postgres_projectdev:
  pgadmin_projectdev: